"""add rule table

Revision ID: 11fdf91169d9
Revises: 08d910599bec
Create Date: 2026-04-19 18:46:38.504664

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "11fdf91169d9"
down_revision: str | Sequence[str] | None = "08d910599bec"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rule",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("pattern", sa.Text(), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("kind IN ('merchant', 'category')", name="ck_rule_kind"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("rule", schema=None) as batch_op:
        batch_op.create_index("ix_rule_kind_priority", ["kind", "priority"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rule", schema=None) as batch_op:
        batch_op.drop_index("ix_rule_kind_priority")

    op.drop_table("rule")
    # ### end Alembic commands ###
